class Cheerleader{



  // constructor
  constructor(attraction, name, img,cheerleaderN) {
    // Position

    // Velocity and speed
    this.x = 0;
    this.y = 0;

    this.img = img;


    // creat a black box which can be generated by calling the boss and use to get more points
    this.attraction=attraction;
    this.size=100; // link the size with boss'power
    this.activeState = false; // used to track if the black box is active
    this.name = name;
    this.cheerleaderEat=0;
    this.cheerleaderCall1=78; // Space key to call the hidden boss, same for both player
    this.cheerleaderCall2=90;
    this.callCount=0;
    this.CheerleaderN=cheerleaderN;

  }


}





}
