class HiddenBoss{


  // constructor
  constructor( size,power,name,img) {
    // Position
    this.x = random(10,800);
    this.y = random(10,500);
    // Velocity and speed
    this.vx = 0;
    this.vy = 0;

    // creat a black box which can be generated by calling the boss and use to get more points
    this.blackBoxSize = power+size; // link the size with boss'power
    this.blackBoxX= this.x; // Must be AFTER defining this.maxHealth
    this.blackBoxY=this.y;
    this.blackBoxState=false;// used to track if the black box is active


  }

  display(){ // display boss and black box
    imageMode(CENTER);
    image(image,this.x,this.y,size,size);
    fill(120);
    rectMode(CORNER);
    rect(this.blackBoxX,this.blackBoxY,this.blackBoxSize,this.blackBoxSize);


}
