class HiddenBoss {


  // constructor
  constructor(size, power, name, img) {
    // Position
  
    // Velocity and speed
    this.x = random(0,1000);
    this.y = random(0,500);
    this.vx = 0;
    this.vy = 0;

    this.img = img;
    this.size = size;

    // creat a black box which can be generated by calling the boss and use to get more points
    this.blackBoxSize = power + size; // link the size with boss'power
    this.blackBoxX = this.x; // Must be AFTER defining this.maxHealth
    this.blackBoxY = this.y;
    this.blackBoxState = false; // used to track if the black box is active
    this.name = name;


  }

  display() { // display boss and black box

    if (this.blackBoxState) {
      //imageMode(CENTER);

      fill(120);
      rectMode(CORNER);
      rect(this.blackBoxX, this.blackBoxY, this.blackBoxSize, this.blackBoxSize);
      image(this.img, this.x, this.y, this.size, this.size);
      fill(255);
      textSize(20);
      text(this.name, 150, 250);


    }
  }
}
